### ISSUE TITLE
On Enter Key Press Event

### ISSUE THREAD

**Issue by eso-digital** [bizzomate/bizzomateNumberInput#3]
We can add On Enter Key Press Event under events. 
We are using your widget and we needed this event. For now I've customized it but it would be good to have a new release with this new event. 

BizzomateNumberInput.xml: [Under OnBlurAction]

                <property key="onEnterKeyPress" type="action" required="false">
                    <caption>On Enter Key Press</caption>
                    <description></description>
                </property>

BizzomateNumberInputProps.d.ts:

Add 
"onEnterKeyPress?: ActionValue; " in both BizzomateNumberInputPreviewProps and BizzomateNumberInputContainerProps interfaces

BizzomateNumberInput.tsx:

Add this :

    // Hande on enter key press event
    const handleOnEnterKeyPress = (event: { key: string; }): void => {
        if(event.key === 'Enter') {
            if (props.onEnterKeyPress && props.onEnterKeyPress.canExecute && !props.onEnterKeyPress.isExecuting) {
                props.onEnterKeyPress.execute();
            }
        }
    };

And the following in <NumericFormat> Tag:

onKeyDown={handleOnEnterKeyPress}

Would be great to see this in new release.

**Comment by JelleDekker** [comment]
Thanks for your input, sounds like a good idea and I'll try to add it to the next release.

**Comment by JelleDekker** [comment]
Released in version 1.4.0, can be downloaded from the Mendix MarketPlace
